[package]
name = "fyrox-book-code"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox = { git = "https://github.com/FyroxEngine/Fyrox", rev = "542c72447b6c2df68cd7151aefa8fb00c80c2bda" }
fyroxed_base = { git = "https://github.com/FyroxEngine/Fyrox", rev = "542c72447b6c2df68cd7151aefa8fb00c80c2bda" }
strum = "0.26.0"
strum_macros = "0.26.0"