[package]
name = "fyrox-book-code"
version = "0.1.0"
edition = "2021"

[dependencies]
fyrox = { git = "https://github.com/FyroxEngine/Fyrox", rev = "0bdb0752524e14c0607a31da5d57e98b45b04553" }
fyroxed_base = { git = "https://github.com/FyroxEngine/Fyrox", rev = "0bdb0752524e14c0607a31da5d57e98b45b04553" }
strum = "0.26.0"
strum_macros = "0.26.0"